# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.0

jobs:
  build:
    docker:
      - image: circleci/jruby:9.1.17.0-jdk
        environment:
          BUNDLER_VERSION: 2.0.2
      - image: jbfavre/vertica:latest
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            gem install bundler -v 2.0.2
      - run:
          name: Bundle Install
          command: |
            bundle install
      - run:
          name: tests
          command: |
            bundle exec rake test
